# Generated by Django 4.0.3 on 2022-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='市町村')),
                ('content', models.TextField(verbose_name='詳細')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='掲載日時')),
                ('category', models.CharField(choices=[('1floor', '一階建'),('2floor', '二階建'),('3floor', '三階建')], max_length=50, verbose_name='階数')),
            ],
        ),
    ]
